### ISSUE TITLE
SEO and social network meta tags

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/blindnet-docs#10]
Add minimum SEO and social network configuration and optimisation.

Partially depends on #7

## Minimal Requirements

> Not exhaustive at all, but it's a minimum we can start with. See the docs for more details.

- [ ] any page can have a coherent and attractive associated card when shared on Twitter (see [Twitter Card Validator](https://cards-dev.twitter.com/validator))
- [ ] most shared pages (starting with the home page) have predefined metadata
- [ ] we have an associated account for [Google Search Console](https://search.google.com/search-console) and the result looks OK

## How to proceed

See https://docusaurus.io/docs/seo
